derbylane/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import path

from two_factor.urls import urlpatterns as tf_urls
from two_factor.gateways.twilio.urls import urlpatterns as tf_twilio_urls

from derbylane.views import (
    FrontPage,
    ProfileView,
    AnalysisView,
    ResultsView,
    WeatherView,
    PasswordReset,
    load_charts,
    load_bets,
    make_bet,
    make_exotic_bet,
    delete_exotic_bet,
    clear_bets,
    get_bets,
    get_venue_bets,
    logout_view,
    change_password,
)
def buildURL(object_name):
    return (
        r'^%s/'
        r'(?P<verb>[a-z_]+)'
        r'(?:\/(?P<obj_id>[0-9A-Za-z_.@-]+))?'
        r'(?:\/(?P<action>[a-z_]+))?/$' % object_name)

urlpatterns = [
    url(r'', include(tf_urls)),
    url(r'', include('django.contrib.auth.urls')),
    url(
        r'^$',
        FrontPage.as_view(),
        name='frontpage'),
    url(
        r'^results/$',
        ResultsView.as_view(),
        name='results'),
    url(
        r'^weather/$',
        WeatherView.as_view(),
        name='weather'),
    url(
        r'^profile/$',
        ProfileView.as_view(),
        name='profile'),
    url(
        r'^analysis/$',
        AnalysisView.as_view(),
        name='analysis'),
    path('', include(tf_twilio_urls)),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('password_reset_form/', auth_views.PasswordChangeView.as_view(), name='password_reset'),
    # path('login/', auth_views.PasswordChangeView.as_view(), name='login'),
    # url(r'password_reset_form/$', auth_views.PasswordResetView.as_view(), name='password_reset_form'),

    # url(r'logout/$', logout_view, name='logout'),
    url(r'change_password/$', change_password, name='change_password'),
    url(r'load_charts/$', load_charts, name='load_charts'),
    url(r'load_bets/$', load_bets, name='load_bets'),
    url(r'get_bets/$', get_bets, name='get_bets'),
    url(r'get_venue_bets/$', get_venue_bets, name='get_venue_bets'),

    url(r'make_bet/$', make_bet, name='make_bet'),
    url(r'make_exotic_bet/$', make_exotic_bet, name='make_exotic_bet'),
    url(r'delete_exotic_bet/$', delete_exotic_bet, name='delete_exotic_bet'),
    url(r'clear_bet/$', clear_bets, name='clear_bets'),
    url(r'password_reset_form/', auth_views.PasswordResetView.as_view(), name ='password_reset'),
]

derbylane/applib/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class CoreModel(models.Model):

    class Meta:
        abstract = True

    created_at = models.DateTimeField()
    created_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='%(app_label)s_%(class)s_created_by')
    modified_at = models.DateTimeField()
    modified_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='%(app_label)s_%(class)s_modified_by')
    uuid = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        primary_key=True)

    def set_fields_to_base(self):
        """
        This method is just a helper. When spawning new objects on the fly,
        request data isn't always available. This method is meant to set the
        created and modified attributes to some automatically available
        defaults.

        This method returns nothing. It justs sets values for the given
        instance.

        Don't abuse this. Use only when a request does not exist.
        """
        self.created_by = User.objects.earliest('pk')
        self.created_at = timezone.now()
        self.modified_by = User.objects.earliest('pk')
        self.modified_at = timezone.now()

rawdat/models.py
import datetime
import os
from django.db import models

from derbylane.applib.models import CoreModel

from itertools import chain

class WeatherLookup(CoreModel):
    """ Specific to wunderground. """
    wunderground = models.CharField(
        null=True,
        max_length=128)
    """ Specific to weatherwidget.io. """
    code = models.CharField(
        null=True,
        max_length=128)
    place = models.CharField(
        null=True,
        max_length=128)
    geocode = models.CharField(
        null=True,
        max_length=128)

class Venue(CoreModel):

    class Meta:
        ordering = ['-name']
        verbose_name = 'Venue'

    name = models.CharField(
        null=True,
        max_length=128)
    code = models.CharField(
        max_length=128)
    is_active = models.BooleanField(default=False)
    is_focused = models.BooleanField(default=False)
    street_number = models.CharField(
        null=True,
        max_length=128)
    street_name = models.CharField(
        null=True,
        max_length=128)
    street_suffix = models.CharField(
        null=True,
        max_length=128)
    city = models.CharField(
        null=True,
        max_length=128)
    state = models.CharField(
        null=True,
        max_length=2,
    )
    zip_code = models.CharField(
        null=True,
        max_length=24)
    country = models.CharField(
        max_length=3,
        default='USA',
    )
    weatherlookup = models.OneToOneField(
        WeatherLookup,
        on_delete=models.CASCADE,
        null=True
    )
    website = models.CharField(
        null=True,
        max_length=256)
    about = models.TextField(
        null=True
    )
    kiosk_name = models.CharField(
        null=True,
        max_length=24)

    def __str__(self):
        return self.name


class Color(CoreModel):

    class Meta:
        verbose_name = 'Color'
        ordering = ['name']

    name = models.CharField(
        max_length=128)

class ScanType(CoreModel):

    name = models.CharField(
        null=True,
        max_length=256)


class Scan(CoreModel):

    comment = models.CharField(
        null=True,
        max_length=256)
    completed_at = models.DateTimeField(null=True)
    type = models.ForeignKey(
        ScanType,
        null=True,
        on_delete=models.CASCADE)


class Litter(CoreModel):

    whelp_date = models.DateField(null=True)
    sire = models.ForeignKey(
        'dog',
        related_name='litter_sire',
        null=True,
        on_delete=models.CASCADE)
    dam = models.ForeignKey(
        'dog',
        related_name='litter_dam',
        null=True,
        on_delete=models.CASCADE)

    def get_litter(self):
        return Dog.objects.filter(litter=self)


class Dog(CoreModel):

    SEX_CHOICES = (
        ('F', 'FEMALE'),
        ('M', 'MALE')
    )

    class Meta:
        ordering = ['name']
        verbose_name = 'Dog'

    name = models.CharField(
        max_length=128)
    sex = models.CharField(
        null=True,
        max_length=1,
        choices=SEX_CHOICES
    )
    color = models.ForeignKey(
        Color,
        null=True,
        on_delete=models.CASCADE)
    litter = models.ForeignKey(
        Litter,
        on_delete=models.CASCADE,
        null=True
    )
    trainer = models.CharField(
        null=True,
        max_length=128)
    set_weight = models.DecimalField(
        null=True,
        max_digits=4,
        decimal_places=2)

    def get_litters(self):
        if self.sex == 'F':
            return Litter.objects.filter(dam=self)
        elif self.sex == 'M':
            return Litter.objects.filter(sire=self)

    def get_absolute_url(self):
        return "/dog/{}/".format(self.uuid)

    def __str__(self):
        return self.name


class Program(CoreModel):

    class Meta:
        verbose_name = 'Program'
        ordering = ['-date']

    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)
    date = models.DateField()

    def get_charts(self):
        return Chart.objects.filter(program=self)

    def get_predicted_charts(self):
        predicted_charts = []
        for chart in self.chart_set.all():
            if chart.has_predictions():
                predicted_charts.append(chart)


class Chart(CoreModel):
    AFTERNOON = 'A'
    EVENING = 'E'
    SCHOOLING = 'S'
    TWILIGHT = 'T'

    TIME_CHOICES = (
        (AFTERNOON, 'Afternoon'),
        (EVENING, 'Evening'),
        (SCHOOLING, 'Schooling'),
        (TWILIGHT, 'Twilight'),
    )

    class Meta:
        verbose_name = 'Chart'
        ordering = ['time']

    program = models.ForeignKey(
        Program,
        null=True,
        on_delete=models.CASCADE)

    time = models.CharField(
        max_length=128,
        choices=TIME_CHOICES
    )
    is_cancelled = models.BooleanField(default=False)


    def kiosk_time(self):
        if self.time == 'A':
            if self.program.venue.code == 'WD':
                return 'Mat'
            else:
                return "Aft"
        elif self.time == 'E':
            return 'Eve'
        elif self.time == 'T':
            return 'Twi'
        else:
            return self.time

    def get_kiosk_name(self):
        return "{}_{}".format(
            self.program.venue.kiosk_name,
            self.kiosk_time())

    # def get_rh(self):
    #     weather = self.program.weather
    #     if weather:
    #         max_rh = weather.max_rh
    #         mean_rh = weather.mean_rh
    #         try:
    #             return float(mean_rh)
    #         except:
    #             pass

    # def get_racetemp(self):
    #     weather = self.program.weather
    #     if weather:
    #         try:
    #             return float(weather.max_temp)
    #         except:
    #             pass

    def get_predicted_races(self):
        predicted_races = []
        for race in self.race_set.all():
            if race.has_predictions():
                predicted_races.append(race)
        return predicted_races

    def has_predictions(self):
        for race in self.race_set.all():
            if race.has_predictions():
                return True

    # def has_bets(self):
    #     for race in self.race_set.all():
    #         if race.has_bets():
    #             return True

    # def is_complete(self):
    #     for race in self.race_set.all():
    #         if not race.is_complete():
    #             return False
    #     return True

class Grade(CoreModel):

    name = models.CharField(
        null=True,
        max_length=3
    )
    value = models.IntegerField(
        null=True
    )

class Condition(CoreModel):

    name = models.CharField(
        null=True,
        max_length=8
    )


class Race(CoreModel):

    FAST = 'F'
    LOOSE = 'L'
    MUDDY = 'M'
    SLOW = 'S'
    WET = 'W'

    GRADE_CHOICES = (
        ('aa', 'AA'),
        ('a', 'A'),
        ('b', 'B'),
        ('c', 'C'),
        ('d', 'D'),
        ('e', 'E'),
        ('j', 'J'),
        ('m', 'M'),
    )

    CONDITION_CHOICES = (
        (FAST, 'Fast'),
        (LOOSE, 'Loose'),
        (MUDDY, 'Muddy'),
        (SLOW, 'Slow'),
        (WET, 'Wet'),
    )

    DISTANCE_CHOICES = (
        (440, '440'),
        (546, '546'),
        (550, '550'),
        (583, '583'),
        (660, '660'),
    )

    class Meta:
        verbose_name = 'Race'
        ordering = ['number']

    chart = models.ForeignKey(
        Chart,
        null=True,
        on_delete=models.CASCADE)
    number = models.IntegerField(
        null=True
    )
    condition = models.ForeignKey(
        Condition,
        null=True,
        on_delete=models.CASCADE)
    grade = models.ForeignKey(
        Grade,
        null=True,
        on_delete=models.CASCADE)
    is_training = models.BooleanField(default=False)
    distance = models.IntegerField(
        choices=DISTANCE_CHOICES,
        null=True)

    def get_straight_predictions(self):
        predictions = []
        for participant in self.participant_set.all():
            if participant.get_recommended_bet():
                predictions.append(participant.get_recommended_bet())
        return predictions

    def get_next(self):
        current_number = self.number
        next_number = current_number + 1
        try:
            return Race.objects.get(chart=self.chart, number=next_number)
        except:
            return False

    def get_previous(self):
        current_number = self.number
        next_number = current_number - 1
        try:
            return Race.objects.get(chart=self.chart, number=next_number)
        except:
            return False

    def has_predictions(self):
        # if "dev" in os.environ['DJANGO_SETTINGS_MODULE']:
        #     return True
        for participant in self.participant_set.all():
            try:
                if participant.get_recommended_bet():
                    return True
            except:
                pass

    def has_bets(self):
        if "dev" in os.environ['DJANGO_SETTINGS_MODULE']:
            return True
        for participant in self.participant_set.all():
            if participant.bet_set.count() > 0:
                return True

    # def get_displayed_participants(self):
    #     all_participants = self.participant_set.all()
    #     if "dev" in os.environ['DJANGO_SETTINGS_MODULE']:
    #         return all_participants
    #     participant_list=[]
    #     if self.is_complete():
    #         for participant in all_participants:
    #             if participant.get_bets().count():
    #                 participant_list.append(participant)
    #     else:
    #         for participant in all_participants:
    #             if participant.get_recommended_bet():
    #                 participant_list.append(participant)
    #     return participant_list

    def is_complete(self):
        for participant in self.participant_set.all():
            if participant.final:
                return True

    def get_participant(self, post):

derbylane/templates/_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'img/favicon-32x32.png' %}" sizes="32x32" type="image/png"/>
    <title>cashdog</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"/></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.js"></script>

  </head>
  <body style="padding: 7px; max-height: 100vh">
    {% include "navbar.html" %}
    <div id="main-content" data-toggle="collapse">
      {% block content %}


      {% endblock content %}
      <script>
      $(document).ready(function () {
        $(document).click(function () {
          $('#navbarToggleExternalContent').collapse('hide')
        });
      });
      </script>
    </div>
  </body>
</html>

derbylane/templates/bet_table.html
{% for race in races %}
<button
  data-toggle="modal"
  data-target="#exotic-modal"
  data-race="{{ race.uuid }}"
  data-venue="{{ race.chart.program.venue.code }}"
  data-time="{{ race.chart.get_time_display }}"
  data-number="{{ race.number }}"
  class="btn btn-sm btn-block btn-outline-primary exotic-bet bet-button"
  style="padding: 0"
  disabled
  >
  <span class="race-number-cell">
    Race {{ race.number }}
  </span>
</button>

{% if race.get_exotic_bets %}
<div id="exotic-wagers-{{ race.uuid }}" style="margin-top: 5px; border-radius: .2rem; ">
{% for wager in race.get_exotic_bets %}
  <div id="{{ wager.uuid }}-wager-div" class="list-group-item exotic-wager-item">
    <span class="exotic-wager-span">${{ wager.amount }} {{ wager.get_name }} {{ wager.get_posts }}</span>
    <button
      type="button"
      data-wageruuid="{{ wager.uuid }}"
      style="display:none"
      class="btn btn-sm btn-outline-danger float-right exotic-delete-button">
      &#10005;
    </button>
  </div>
{% endfor %}
</div>
{% endif %}


<table
  id="main-table"
  class="table table-sm table-borderless fade-in"
  style="margin:5px 0px;">
  {% for participant in race.participant_set.all %}
    {% if participant.get_recommended_bet %}
      <tr>
        <td>
          <button
            type="button"
            class="btn btn-outline-success btn-block btn-sm bet-button"
            data-toggle="modal"
            data-target="#straight-bet-modal"
            data-dog="{{ participant.dog.name }}"
            data-post="{{ participant.post }}"
            data-bets="{{ participant.get_recommended_bet }}"
            data-venue="{{ participant.race.chart.program.venue.code }}"
            data-chart="{{ participant.race.chart.get_time_display }}"
            data-number="{{ participant.race.number }}"
            data-participant="{{ participant.uuid }}"
            data-bets="{{ participant.get_recommended_bet }}"
            >
            {{ participant.post }}
            <span
              class="dog-name-span">
              {{ participant.dog.name|truncatechars:8 }}
            </span>
          </button>
        </td>

        <td id="{{ participant.uuid }}-win-td">
          {% if participant.get_win_bet %}
            <button
              id="{{ participant.uuid }}-win-button"
              class="btn btn-sm btn-block btn-outline-info quick-bet-btn"
              disabled>
                {{ participant.get_win_bet.purchase_amount }}
            </button>
          {% else %}
            {% if 'W' in participant.get_recommended_bet %}
              <button
                id="{{ participant.uuid }}-win-button"
                class="btn btn-sm btn-block btn-outline-light quick-bet-btn"
                data-participant="{{ participant.uuid }}"
                data-type="W"
                disabled>
                W
              </button>
            {% endif %}
          {% endif %}
        </td>
        <td id="{{ participant.uuid }}-place-td" >
          {% if participant.get_place_bet %}
            <button
              id="{{ participant.uuid }}-place-button"
              class="btn btn-sm btn-block btn-outline-info quick-bet-btn"
              disabled>
                {{ participant.get_place_bet.purchase_amount }}
            </button>
          {% else %}
            {% if 'P' in participant.get_recommended_bet %}
              <button
                id="{{ participant.uuid }}-place-button"
                class="btn btn-sm btn-block btn-outline-light quick-bet-btn"
                data-participant="{{ participant.uuid }}"
                data-type="P"
                disabled>
                P
              </button>
            {% endif %}
          {% endif %}
        </td>
        <td id="{{ participant.uuid }}-show-td">
          {% if participant.get_show_bet %}
            <button
              id="{{ participant.uuid }}-show-button"
              class="btn btn-sm btn-block btn-outline-info quick-bet-btn"
              disabled>
                {{ participant.get_show_bet.purchase_amount }}
            </button>
          {% else %}
            {% if 'S' in participant.get_recommended_bet %}
              <button
                id="{{ participant.uuid }}-show-button"
                class="btn btn-sm btn-block btn-outline-light quick-bet-btn"
                data-participant="{{ participant.uuid }}"
                data-type="S"
                disabled>
                S
              </button>
            {% endif %}
          {% endif %}
        </td>
      {% endif %}
    </tr>
  {% endfor %}
</table>
{% endfor %}

<script>
  exotic_wager_buttons = document.getElementsByClassName("exotic-wager-item")
  for (let i=0; i<exotic_wager_buttons.length; i++) {
    exotic_wager_buttons[i].addEventListener("click", toggle_delete_show)
  }

  exotic_delete_buttons = document.getElementsByClassName("exotic-delete-button")
  for (let i=0; i<exotic_delete_buttons.length; i++) {
    exotic_delete_buttons[i].addEventListener("click", handle_exotic_delete)
  }


  quick_bet_buttons = document.getElementsByClassName("quick-bet-btn")
  for (let i=0; i< quick_bet_buttons.length; i++) {
    quick_bet_buttons[i].addEventListener("click", quickbet)
  }
</script>

<br/>

<br/>  <br/>  <br/>  <br/>  <br/>  <br/>  <br/>  <br/>  <br/>

derbylane/templates/frontpage.html
{% extends '_base.html'%}
{% load static %}

{% block content %}
  <div
    id="main-card-header"
    class="card-header">
    {% if previous %}
    <a
      class="btn btn-small"
      href="{% url 'frontpage' %}?date={{ previous }}">
      <img
        src="{% static 'img/back.png' %}"
        height=20
        class="float-left date_arrow"
        alt="back-icon">
    </a>
    {% else %}
    <a
      class="btn btn-small disabled"
      href="{% url 'frontpage' %}?date={{ previous }}">
      <img
        src="{% static 'img/back.png' %}"
        height=20
        class="float-left date_arrow"
        alt="back-icon">
    </a>
    {% endif %}
    <span
      id="date_header"
      class="text-center"
      style="font-size: 1.6em; margin:auto; font-style: italic; font-weight: bold">
        {{ date_header }}
    </span>
    {% if next %}
    <a
      class="btn btn-small"
      href="{% url 'frontpage' %}?date={{ next }}">
      <img
        src="{% static 'img/forward.png' %}"
        height=20
        class="float-left date_arrow"
        alt="forward-icon">
    </a>
    {% else %}
    <a
      class="btn btn-small disabled"
      href="{% url 'frontpage' %}?date={{ next }}">
      <img
        src="{% static 'img/forward.png' %}"
        style="display:inline"
        height=20
        class="float-left"
        alt="forward-icon">
    </a>
    {% endif %}
  </div>

  {% if charts|length %}
    <div
      id="charts-holder"
      class="select-holder">
      <select
        class="form-control frontpage-select dropdown-toggle"
        id="chart-select"
        onchange="load_bets()">
        {% for chart in charts %}
          <option value="{{ chart.uuid }}">
            <span>
              {{ chart.program.venue.name }} {{chart.kiosk_time }}
            </span>
          </option>
        {% endfor %}
      </select>
    </div>
    <div id="bets" style="max-height: 75vh; overflow-y: scroll">
      <img
        id="loader-gif"
        src="{% static 'img/preloader.gif' %}"
        height="80px"
        class="center"
        alt="spinner-gif">
    </div>

    {% include 'straightmodal.html' %}
    {% include 'exoticmodal.html' %}
  {% else %}
    <div
      id="empty-charts-div">
      No Charts Today
    </div>
  {% endif %}




  <script id="json-chart-data" type="application/json">
    {
      "bets_url": "{% url 'load_bets' %}",
      "results_url": "{% url 'results' %}",
      "make_bets_url": "{% url 'make_bet' %}",
      "make_exotic_bet_url": "{% url 'make_exotic_bet' %}",
      "delete_exotic_bet_url": "{% url 'delete_exotic_bet' %}",
      "clear_bets_url": "{% url 'clear_bets' %}"
    }
  </script>

  <script src="{% static 'js/frontpage.js' %}"></script>

  {% endblock content %}

derbylane/templates/load_bets.html
<!-- {% if wagering %}
  {% for race in races %}
    {% if race.has_predictions %}
      {% include 'race_table.html' %}
    {% endif %}
  {% endfor %}
{% else %}
  {% for race in races %}
    {% if race.has_bets %}
      {% include 'results_table.html' %}
    {% endif %}
  {% endfor %}
{% endif %} -->

derbylane/templates/load_charts.html
{% for chart in charts %}
  <option value="{{ chart.uuid }}">
    {{ chart.program.venue.code }} {{ chart.get_time_display }}
  </option>
{% endfor %}

derbylane/templates/new_table.html
{% for race in races %}
<button
  data-toggle="modal"
  data-target="#exotic-modal"
  data-race="{{ race.uuid }}"
  data-venue="{{ race.chart.program.venue.code }}"
  data-time="{{ race.chart.get_time_display }}"
  data-number="{{ race.number }}"
  class="btn btn-sm btn-block btn-outline-primary exotic-bet bet-button">
  <span class="race-number-cell">
    Race {{ race.number }}
  </span>
</button>

{% if race.get_exotic_bets %}
<div id="exotic-wagers-{{ race.uuid }}" style="margin-top: 10px; border-radius: .2rem; ">
{% for wager in race.get_exotic_bets %}
  <div id="{{ wager.uuid }}-wager-div" class="list-group-item exotic-wager-item">
    <span class="exotic-wager-span">${{ wager.amount }} {{ wager.get_name }} {{ wager.get_posts }}</span>
    <button
      type="button"
      data-wageruuid="{{ wager.uuid }}"
      style="display:none"
      class="btn btn-sm btn-outline-danger float-right exotic-delete-button">
      &#10005;
    </button>
  </div>
{% endfor %}
</div>
{% endif %}


<table
  id="main-table"
  class="table table-sm table-borderless fade-in">
  {% for participant in race.participant_set.all %}
    {% if participant.get_recommended_bet %}
    <tr>
      <td>
        {{ participant.post }}
        <span
          class="dog-name-span">
          {{ participant.dog.name|truncatechars:13 }}
      </td>
      <td>
        <button
          type="button"
          class="btn btn-outline-success btn-block btn-sm bet-button"
          data-toggle="modal"
          data-target="#straight-bet-modal"
          data-dog="{{ participant.dog.name }}"
          data-post="{{ participant.post }}"
          data-bets="{{ participant.get_recommended_bet }}"
          data-venue="{{ participant.race.chart.program.venue.code }}"
          data-chart="{{ participant.race.chart.get_time_display }}"
          data-number="{{ participant.race.number }}"
          data-participant="{{ participant.uuid }}"
          data-bets="{{ participant.get_recommended_bet }}"
          disabled>
          <span id="participant_bets">
             {{ participant.get_recommended_bet }}
          </span>
        </button>
      </td>
    {% endif %}
    <!--
      <td id="{{ participant.uuid }}-win-td">
        <button
          class="btn btn-sm btn-block btn-outline-light"
          disabled>
          ${{ participant.get_win_bet.amount }}
        </button>
      </td>
      <td id="{{ participant.uuid }}-place-td">
        <button
          class="btn btn-sm btn-block btn-outline-light"
          disabled>
          P
        </button>
      </td>
      <td id="{{ participant.uuid }}-show-td">
        <button
          class="btn btn-sm btn-block btn-outline-light"
          disabled>
          S
        </button>
      </td> -->
    </tr>
  {% endfor %}
</table>
{% endfor %}

<script>
  exotic_wager_buttons = document.getElementsByClassName("exotic-wager-item")
  for (let i=0; i<exotic_wager_buttons.length; i++) {
    exotic_wager_buttons[i].addEventListener("click", toggle_delete_show)
  }

  exotic_delete_buttons = document.getElementsByClassName("exotic-delete-button")
  for (let i=0; i<exotic_delete_buttons.length; i++) {
    exotic_delete_buttons[i].addEventListener("click", handle_exotic_delete)
  }
</script>

<br/>

<br/>  <br/>  <br/>  <br/>  <br/>  <br/>  <br/>  <br/>  <br/>

derbylane/templates/profile.html
{% extends '_base.html' %}

{% block content %}

<p><a href="{% url 'password_reset' %}">Reset Password</a></p>

{% endblock content %}

derbylane/templates/summary.html
{% extends '_base.html'%}

hey

derbylane/templates/welcome.html
{% extends '_base.html'%}

{% block content %}
{% if user.is_authenticated %}
Welcome, {{ user }}

{% else %}




{% endif %}
{% endblock content %}